export interface Lesson {
  slug: string;
  number: string;
  title: string;
  module: string;
  summary: string;
  free: boolean;
}

export const lessons: Lesson[] = [
  {
    slug: "00-preface",
    number: "0",
    title: "前言：點解你一定要學 AI",
    module: "入門篇",
    summary: "AI Agent 唔係聊天機械人，佢而家有手有腳，可以直接幫你做完一項工作。",
    free: true,
  },
  {
    slug: "01-install-opencode",
    number: "1",
    title: "安裝 OpenCode Desktop",
    module: "入門篇",
    summary: "下載、安裝、揀模型，5分鐘搞掂。",
    free: true,
  },
  {
    slug: "02-merge-excel",
    number: "2",
    title: "做你第一個效率工具：合併 Excel",
    module: "入門篇",
    summary: "用 AI 幾分鐘做出一個有圖形介面嘅 Excel 合併工具。",
    free: true,
  },
  {
    slug: "03-choose-model",
    number: "3",
    title: "揀啱你嘅大模型",
    module: "入門篇",
    summary: "OpenCode 支援咩模型？免費 vs 付費點揀？",
    free: true,
  },
  {
    slug: "04-opencode-tui",
    number: "4",
    title: "安裝 OpenCode 終端版",
    module: "入門篇",
    summary: "一行指令安裝，TUI 介面基本操作。",
    free: true,
  },
  {
    slug: "05-opencode-plugins",
    number: "5",
    title: "安裝 OpenCode 增強插件",
    module: "技能篇",
    summary: "Superpowers、oh-my-opencode-slim 插件安裝同配置。",
    free: false,
  },
  {
    slug: "06-learn-skills",
    number: "6",
    title: "以 Skill 為例學識點樣學習",
    module: "技能篇",
    summary: "Skill 係乜？點樣用 AI 輔助學習？",
    free: false,
  },
  {
    slug: "07-mineru-install",
    number: "7",
    title: "MinerU Skill 安裝：AI 讀懂掃描 PDF",
    module: "技能篇",
    summary: "66K Stars 開源 PDF 解析引擎，安裝同配置。",
    free: false,
  },
  {
    slug: "08-mineru-invoice-contract",
    number: "8",
    title: "MinerU 提取發票、合同關鍵資訊",
    module: "技能篇",
    summary: "批量辨識發票、提取合同條款、AI 合同審查。",
    free: false,
  },
  {
    slug: "09-find-skills",
    number: "9",
    title: "用 find-skills 搵你想要嘅 Skill",
    module: "技能篇",
    summary: "一句話搜尋多個 Skill 社區。",
    free: false,
  },
  {
    slug: "10-skill-creator",
    number: "10",
    title: "安裝神級 Skill：Skill Creator",
    module: "技能篇",
    summary: "Anthropic 官方出品，將操作流程自動化為可重用 Skill。",
    free: false,
  },
  {
    slug: "11-skill-practice-word",
    number: "11",
    title: "Word 報告格式調整實戰 Skill",
    module: "技能篇",
    summary: "用 python-docx 學習 Word 格式規範，打包成 Skill。",
    free: false,
  },
  {
    slug: "12-word-efficiency-tool",
    number: "12",
    title: "Word 報告格式效率工具",
    module: "技能篇",
    summary: "用 Oh My OpenCode Slim 插件，AI 自動排程多個子 Agent 協作。",
    free: false,
  },
  {
    slug: "13-voice-input",
    number: "13",
    title: "三款 AI 語音輸入法",
    module: "技能篇",
    summary: "豆包、GLM、openless，按住講嘢鬆手出字。",
    free: false,
  },
  {
    slug: "14-distill-anyone",
    number: "14",
    title: "以蒸餾陳版主為例——蒸餾任何人",
    module: "實戰篇",
    summary: "女媧 Skill 將任何人嘅思維方式蒸餾成可重用 Skill。",
    free: false,
  },
  {
    slug: "15-merge-skills",
    number: "15",
    title: "兩個 Skill 合併",
    module: "實戰篇",
    summary: "將視角 Skill 同 BBS 檢索 Skill 合併成更強大版本。",
    free: false,
  },
  {
    slug: "16-ai-remember-you",
    number: "16",
    title: "等 AI 記住你",
    module: "實戰篇",
    summary: "CLAUDE.md / AGENTS.md 記憶檔嘅原理同用法。",
    free: false,
  },
  {
    slug: "17-ima-knowledge-base",
    number: "17",
    title: "AI 呼叫 IMA 知識庫",
    module: "實戰篇",
    summary: "MCP 協定同 IMA 知識庫整合，解決 AI 幻覺問題。",
    free: false,
  },
  {
    slug: "18-terminal-commands",
    number: "18",
    title: "終端版常用指令",
    module: "實戰篇",
    summary: "模式切換、上下文管理、斜杠指令速查。",
    free: false,
  },
  {
    slug: "19-ask-ai-properly",
    number: "19",
    title: "點樣同 AI 提問",
    module: "實戰篇",
    summary: "提問四要素、準確率黃金法則、迭代策略。",
    free: false,
  },
  {
    slug: "20-git-version-control",
    number: "20",
    title: "用 Git 做版本控制",
    module: "實戰篇",
    summary: "AI 改 code 越改越爛？版本控制 = 遊戲存檔。",
    free: false,
  },
  {
    slug: "21-warp-terminal",
    number: "21",
    title: "安裝更友好嘅 Warp 終端",
    module: "實戰篇",
    summary: "現代化終端，複製貼上正常、指令自動補全。",
    free: false,
  },
  {
    slug: "22-deepseek-vision",
    number: "22",
    title: "等 DeepSeek 識睇圖",
    module: "實戰篇",
    summary: "用 oh-my-opencode-slim 嘅 observer 子代理配識圖模型。",
    free: false,
  },
  {
    slug: "23-vision-mcp",
    number: "23",
    title: "用 MCP 等任何 AI 都識睇圖",
    module: "實戰篇",
    summary: "Vision MCP 通用方案，跨工具適用。",
    free: false,
  },
  {
    slug: "24-connect-im",
    number: "24",
    title: "將 AI 裝入 WhatsApp",
    module: "實戰篇",
    summary: "cc-connect 開源工具，橋接到即時通訊軟件。",
    free: false,
  },
  {
    slug: "25-claude-code-install",
    number: "25",
    title: "安裝 Claude Code",
    module: "實戰篇",
    summary: "Anthropic 官方 CLI 工具，同 OpenCode 相容。",
    free: false,
  },
  {
    slug: "26-data-cockpit-architecture",
    number: "26",
    title: "數據駕駛艙：用 AI 搞定複雜系統",
    module: "高階篇",
    summary: "先搭鋼架再修牆，完整流程六步。",
    free: false,
  },
  {
    slug: "27-data-cockpit-implementation",
    number: "27",
    title: "數據駕駛艙：實施推進與權限落地",
    module: "高階篇",
    summary: "驗收 MVP、逐步迭代、權限基建。",
    free: false,
  },
  {
    slug: "28-data-cockpit-deploy",
    number: "28",
    title: "數據駕駛艙：部署上線",
    module: "高階篇",
    summary: "SSH 匙羹交俾 AI，連 server 都幫你搞掂。",
    free: false,
  },
  {
    slug: "29-exam-prep",
    number: "29",
    title: "用 AI 工具備考任何考試",
    module: "高階篇",
    summary: "Pass All Exams 工具，一句話安裝。",
    free: false,
  },
  {
    slug: "30-ai-browser",
    number: "30",
    title: "等 AI 學識操作瀏覽器",
    module: "高階篇",
    summary: "Playwright MCP + CLI，AI 直接操控瀏覽器。",
    free: false,
  },
  {
    slug: "31-china-law-search",
    number: "31",
    title: "實戰：法規查詢 Skill",
    module: "高階篇",
    summary: "讓 AI 做一個能批量查法規、下载法規嘅 Skill。",
    free: false,
  },
  {
    slug: "32-cicpa-company-query",
    number: "32",
    title: "實戰：工商資訊查詢 Skill",
    module: "高階篇",
    summary: "有登入、有滑塊驗證碼嘅會員制系統操作。",
    free: false,
  },
  {
    slug: "33-related-party",
    number: "33",
    title: "製作關聯方識別 Skill",
    module: "高階篇",
    summary: "用監管處罰案例反推關聯方點樣被發現。",
    free: false,
  },
  {
    slug: "34-wx-cli",
    number: "34",
    title: "等 AI 讀取 WhatsApp 紀錄",
    module: "高階篇",
    summary: "開源工具，直接讀取本地聊天紀錄。",
    free: false,
  },
  {
    slug: "35-ai-report-checker",
    number: "35",
    title: "AI 覆核會計報告",
    module: "專業篇",
    summary: "AI 做語義，code 做算術，三層架構覆核報表。",
    free: false,
  },
  {
    slug: "36-local-rag-knowledge-base",
    number: "36",
    title: "本地 RAG 知識庫",
    module: "專業篇",
    summary: "RAG 五步流程：解析→切片→向量化→存入→語義檢索。",
    free: false,
  },
  {
    slug: "37-voice-to-text",
    number: "37",
    title: "語音轉文字：會議記錄同字幕",
    module: "專業篇",
    summary: "本地 Whisper / API 方案 / 零配置工具通義聽悟。",
    free: false,
  },
  {
    slug: "38-ai-excel",
    number: "38",
    title: "AI 操作 Excel：三種方案",
    module: "專業篇",
    summary: "Pandas + OpenPyXL / Xlwings / Win32com 點揀。",
    free: false,
  },
  {
    slug: "39-ai-accounting-wp",
    number: "39",
    title: "AI 生成會計工作底稿",
    module: "專業篇",
    summary: "實戰同避坑指南，原子化 Skill 設計。",
    free: false,
  },
  {
    slug: "40-audit-review-skill",
    number: "40",
    title: "工作底稿覆核 Skill 設計框架",
    module: "專業篇",
    summary: "四步框架：確定範圍→公式檢查→完整性→輸出報告。",
    free: false,
  },
  {
    slug: "41-excel-ai-agent",
    number: "41",
    title: "Excel AI Agent 插件",
    module: "擴展篇",
    summary: "喺 Excel 入面直接同 AI 對話操作。",
    free: false,
  },
  {
    slug: "42-flowchart-skill",
    number: "42",
    title: "等 AI 幫你畫會計流程圖",
    module: "擴展篇",
    summary: "draw.io XML 批量生成泳道圖。",
    free: false,
  },
  {
    slug: "43-next-ai-drawio",
    number: "43",
    title: "Next AI Draw.io 對話式流程圖",
    module: "擴展篇",
    summary: "整合 AI Agent，自然語言生成流程圖。",
    free: false,
  },
  {
    slug: "44-ai-ppt",
    number: "44",
    title: "AI 做 PPT 嘅兩種路線",
    module: "擴展篇",
    summary: "HTML 路線 vs PPT 路線，先揀路線再揀工具。",
    free: false,
  },
  {
    slug: "45-opendesign-pencil",
    number: "45",
    title: "OpenDesign 同 Pencil 製作 PPT",
    module: "擴展篇",
    summary: "可視化設計工具，補足 HTML 路線嘅短板。",
    free: false,
  },
];

export const modules = [
  "入門篇",
  "技能篇",
  "實戰篇",
  "高階篇",
  "專業篇",
  "擴展篇",
] as const;

export function getLesson(slug: string): Lesson | undefined {
  return lessons.find((l) => l.slug === slug);
}
